---
language: python
before_install:
  - npm install stylus@0.27.2; npm install nib@0.5.0
install:
  - pip install coveralls
python:
  - "2.7"
  - "3.3"

# command to run tests
script: python setup.py nosetests

after_success: coveralls
